import Image from "next/image";
import Link from "next/link";
import { AdminPanel, PageHeader, PrimaryLink, StatusBadge } from "@/components/admin/admin-ui";
import { listProfessionals } from "@/lib/cms/repository";
import { requireAdmin } from "@/lib/auth/admin";
import { createServerSupabaseClient } from "@/lib/supabase/server";
export default async function TeamList() {
 const admin = await requireAdmin(); const people = await listProfessionals(true); const client = await createServerSupabaseClient();
 const signedImages = new Map(await Promise.all(people.filter((person) => person.profile_image_url).map(async (person) => { const path = person.profile_image_url.replace("/api/public/media/content/", ""); const { data } = await client.storage.from("content-images").createSignedUrl(path, 300); return [person.id, person.profile_image_url.startsWith("/images/") ? person.profile_image_url : data?.signedUrl] as const; })));
 return <><PageHeader actions={admin.role !== "viewer" ? <PrimaryLink href="/admin/equipo/nuevo">Nuevo profesional</PrimaryLink> : undefined} description="Publicación y orden del equipo. Cada perfil publicado aparece automáticamente en la web." eyebrow="CMS" title="Equipo" /><AdminPanel className="admin-table-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Foto</th><th>Nombre</th><th>Cargo</th><th>Estado</th><th>Destacado</th><th>Orden</th><th>Actualizado</th><th>Acciones</th></tr></thead><tbody>{people.map((person) => <tr key={person.id}><td data-label="Foto">{signedImages.get(person.id) ? <Image alt={person.profile_image_alt} height={64} src={signedImages.get(person.id)!} unoptimized width={48} /> : "Sin foto"}</td><td data-label="Nombre">{person.full_name}</td><td data-label="Cargo">{person.role}</td><td data-label="Estado"><StatusBadge value={person.status} /></td><td data-label="Destacado">{person.is_featured ? "Sí" : "No"}</td><td data-label="Orden">{person.sort_order}</td><td data-label="Actualizado">{new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeZone: "America/Santiago" }).format(new Date(person.updated_at))}</td><td data-label="Acciones"><div className="admin-table-actions">{admin.role !== "viewer" && <><Link href={`/admin/equipo/${person.id}`}>Editar perfil</Link><Link href={`/admin/equipo/${person.id}#fotografia`}>Subir foto</Link></>}<Link href={`/admin/equipo/${person.id}/vista-previa`}>Vista previa</Link>{person.status === "published" && <Link href={`/equipo/${person.slug}`}>Ver perfil</Link>}</div></td></tr>)}</tbody></table></div></AdminPanel></>;
}
