import { randomUUID } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { blockSchema, professionalSchema, settingsSchema } from "../src/lib/cms/schemas.ts";

// Editorial source: CASTELAO_CHILE_CMS_EQUIPO_CODEX.md, sections 8 and 32–39.
// Only initial data; public renderers never import this seed or old provisional copy.
const cta = { label: "Agendar evaluación", target: "evaluation", href: "/contacto" };
const whatsapp = { label: "WhatsApp", target: "whatsapp", href: "/contacto" };
const images = {
  hero: { src: "/images/hero-sala-luminosa.webp", alt: "Sala luminosa del Instituto Castelao" },
  institute: { src: "/images/instituto-sala-azul.webp", alt: "Interior de una sala del Instituto Castelao" },
  group: { src: "/images/acompanamiento-sala-grupal.webp", alt: "Sala preparada para un espacio de conversación" },
  contact: { src: "/images/contacto-sala-de-espera.webp", alt: "Sala de espera con luz natural" },
};
const block = (section_type: string, data: unknown) => ({ section_type, data });
const hero = (title: string, description: string, image = images.hero) => block("hero", { title, description, eyebrow: "Instituto Castelao Chile", variant: "blue", image, primaryCta: cta, secondaryCta: whatsapp });
const prose = (title: string, description: string, html: string) => block("rich_text", { title, description, html });
const cards = (title: string, titles: string[], section_type = "feature_cards") => block(section_type, { title, description: "", items: titles.map((title) => ({ title, description: "" })) });
const pricing = (title: string, price: number, unit: string, note: string) => block("pricing", { title: "Valores", description: "", items: [{ title, price, unit, note }] });
const contactCta = (title: string, description = "") => block("cta", { title, description, primaryCta: cta, secondaryCta: whatsapp });
const faq = block("faq", { title: "Preguntas frecuentes", description: "Información para pacientes y familias.", items: [
  { question: "¿Cuánto cuesta la evaluación inicial?", answer: "La evaluación inicial tiene un valor de $35.000 CLP.", category: "Evaluación", is_enabled: true },
  { question: "¿Cuál es el valor del programa ambulatorio?", answer: "El Programa Ambulatorio tiene un valor de $550.000 CLP mensuales. La coordinación psiquiátrica se considera cuando corresponde; la atención psiquiátrica no está incluida en la mensualidad.", category: "Tratamiento", is_enabled: true },
  { question: "¿Recovery 40 reemplaza una desintoxicación médica?", answer: "No. Recovery 40 no es una hospitalización ni reemplaza una desintoxicación médica cuando esta es necesaria.", category: "Recovery 40", is_enabled: true },
  { question: "¿La familia participa en el proceso?", answer: "El tratamiento contempla trabajo semanal con familias. La familia también necesita recuperación.", category: "Familias", is_enabled: true },
  { question: "¿Este sitio atiende situaciones de urgencia?", answer: "No. Este sitio no es un canal de urgencias. Ante una situación inmediata, busca apoyo a través de los servicios de emergencia o de salud de tu localidad.", category: "Contacto", is_enabled: true },
] });
const pages = [
  { slug: "inicio", path: "/", title: "Inicio", nav_label: "Inicio", sections: [hero("Dejar de consumir es sólo el comienzo.", "Tratamiento ambulatorio especializado en adicciones para pacientes y familias."), prose("Una recuperación en la vida real", "Modelo Minnesota · Terapia grupal · Psicología · Familia · Seguimiento terapéutico", "<p>El tratamiento va más allá del consumo y contempla el acompañamiento de pacientes y familias.</p>"), cards("Conoce Castelao Chile", ["Tratamiento ambulatorio", "Recovery 40", "Trabajo con familias"]), pricing("Evaluación inicial", 35000, "Evaluación", "La evaluación inicial orienta los siguientes pasos."), block("team_preview", { title: "Nuestro equipo", description: "Profesionales y personas con experiencia especializada en acompañar procesos de recuperación.", featuredOnly: true }), contactCta("Da el primer paso")] },
  { slug: "el-instituto", path: "/instituto", title: "El Instituto", nav_label: "El Instituto", sections: [hero("Instituto Castelao Chile", "Tratamiento ambulatorio especializado en adicciones para pacientes y familias.", images.institute), prose("Más allá del consumo", "Comprender la adicción y acompañar la recuperación.", "<p>Dejar de consumir es sólo el comienzo. La recuperación contempla la vida cotidiana, la responsabilidad personal y el trabajo con la familia.</p><p>La relación metodológica con Instituto Castelao España se expresa en el Modelo Minnesota y el seguimiento terapéutico. La información de Chile se presenta según su contexto local.</p>"), cards("Nuestros principios", ["Abstinencia", "Reconocimiento", "Responsabilidad", "Honestidad", "Estructura", "Familia", "Continuidad"], "principles"), block("team_preview", { title: "Dirección y equipo", description: "Conoce a los profesionales de Castelao Chile.", featuredOnly: false }), contactCta("Conversa con nosotros")] },
  { slug: "tratamiento", path: "/acompanamiento", title: "Tratamiento", nav_label: "Tratamiento", sections: [hero("Tratamiento ambulatorio especializado en adicciones", "Acompañamiento para pacientes y familias.", images.group), cards("Qué contempla el tratamiento", ["Terapia grupal", "Intervención individual de adicciones", "Psicoterapia individual", "Trabajo semanal con familias", "Seguimiento cotidiano", "Actividad física terapéutica", "Prevención de recaídas", "Controles toxicológicos cuando sean indicados", "Coordinación psiquiátrica cuando corresponda"]), pricing("Programa Ambulatorio", 550000, "Mensuales", "La atención psiquiátrica no está incluida en la mensualidad."), contactCta("Agenda una evaluación inicial")] },
  { slug: "recovery-40", path: "/recovery-40", title: "Recovery 40", nav_label: "Recovery 40", sections: [hero("Recovery 40", "Programa de 40 días, sujeto a evaluación y condiciones de ingreso.", images.group), prose("Para quién está indicado", "El ingreso se define mediante evaluación individual.", "<p>La evaluación permite revisar la situación de la persona y las condiciones de ingreso al programa.</p>"), cards("Objetivos del proceso", ["Recuperación en la vida real", "Prevención de recaídas", "Seguimiento terapéutico"]), prose("Continuidad posterior", "El proceso de recuperación continúa después de los 40 días.", "<p>Los siguientes pasos y el acompañamiento posterior se revisan mediante evaluación profesional.</p>"), pricing("Recovery 40", 4500000, "Por 40 días", "Valor referencial, sujeto a evaluación y condiciones de ingreso."), block("warning", { title: "Advertencia clínica", description: "Recovery 40 no es una hospitalización ni reemplaza una desintoxicación médica cuando esta es necesaria." }), contactCta("Consulta sobre Recovery 40")] },
  { slug: "nuestro-metodo", path: "/nuestro-enfoque", title: "Nuestro método", nav_label: "Nuestro método", sections: [hero("Nuestro método", "Modelo Minnesota y enfoque cognitivo-conductual-contextual."), cards("Recuperación en la vida real", ["Modelo Minnesota", "Enfoque cognitivo-conductual-contextual", "Prevención de recaídas"]), cards("Continuidad del proceso", ["Base del Camino", "Medio Camino"], "steps"), prose("Señales previas a una recaída", "Reconocer cambios y pedir acompañamiento forma parte de la prevención.", "<p>Las señales y circunstancias personales se abordan con el equipo durante el seguimiento terapéutico. Esta información general no reemplaza una evaluación individual.</p>"), contactCta("Conoce el proceso de evaluación")] },
  { slug: "familias", path: "/familias", title: "Familias", nav_label: "Familias", sections: [hero("La familia también necesita recuperación.", "Acompañamiento para quienes están cerca de una persona en proceso de recuperación.", images.contact), prose("Trabajo con familias", "El tratamiento contempla trabajo semanal con familias.", "<p>La recuperación considera a las personas y su entorno. El acompañamiento ofrece un espacio para trabajar con las familias durante el proceso.</p>"), block("cta", { title: "Quiero orientación para un familiar", description: "Conversa con nosotros sobre los siguientes pasos.", primaryCta: { label: "Quiero orientación para un familiar", target: "custom", href: "/contacto" }, secondaryCta: whatsapp })] },
  { slug: "equipo", path: "/equipo", title: "Equipo", nav_label: "Equipo", sections: [hero("Nuestro equipo", "Profesionales y personas con experiencia especializada en acompañar procesos de recuperación.", images.institute), block("team_preview", { title: "Profesionales de Castelao Chile", description: "Conoce su experiencia y mirada sobre la recuperación.", featuredOnly: false }), contactCta("Conversa con nuestro equipo")] },
  { slug: "preguntas-frecuentes", path: "/preguntas-frecuentes", title: "Preguntas frecuentes", nav_label: "Preguntas frecuentes", sections: [hero("Preguntas frecuentes", "Respuestas para comenzar a conocer nuestro tratamiento.", images.institute), faq, contactCta("¿Necesitas orientación?")] },
  { slug: "contacto", path: "/contacto", title: "Contacto", nav_label: "Contacto", sections: [hero("Conversa con Instituto Castelao Chile", "Da el primer paso para una evaluación inicial.", images.contact), pricing("Evaluación inicial", 35000, "Evaluación", "El sistema definitivo de agenda se confirmará institucionalmente."), block("contact", { title: "Contacto", description: "Utiliza nuestros canales confirmados para solicitar información. No compartas antecedentes sensibles de salud en este formulario." }), block("warning", { title: "Este sitio no es un canal de urgencias", description: "Ante una situación inmediata, busca apoyo a través de los servicios de emergencia o de salud disponibles en tu localidad." })] },
];
const person = professionalSchema.parse({
  full_name: "Marcelo Montiel Arzola", slug: "marcelo-montiel", role: "Director Instituto Castelao Chile", credentials: ["Terapeuta en Adicciones", "Intervencionista Familiar", "Coach ICC"],
  short_bio: "Experiencia en acompañar a pacientes y familias en procesos de recuperación.",
  bio: "<p>Marcelo Montiel Arzola es Director de Instituto Castelao Chile, Terapeuta en Adicciones, Intervencionista Familiar y Coach ICC.</p>",
  professional_experience: "<p>Experiencia con pacientes y familias e intervención en crisis.</p>", recovery_experience: "<p>Más de veinte años de recuperación personal.</p>",
  featured_quote: "No me interesa solamente que una persona deje de consumir. Me interesa saber cómo va a vivir después.",
  media: "Participación en televisión y radio.", conferences: "Charlas y conferencias sobre recuperación.",
  profile_image_url: "", profile_image_alt: "", email: "", phone: "", linkedin_url: "", instagram_url: "",
  cta_label: "Solicitar información sobre charlas", cta_url: "/contacto", is_featured: true, status: "published", sort_order: 0,
  seo_title: "Marcelo Montiel | Instituto Castelao Chile", seo_description: "Conoce a Marcelo Montiel Arzola, Director de Instituto Castelao Chile, y su experiencia en acompañar a pacientes y familias.",
});
const settings = settingsSchema.parse({ whatsapp: "+56938650977", phone: "", email: "", streetAddress: "", city: "", region: "", country: "", mapsUrl: "", instagram: "", facebook: "", linkedin: "", evaluationUrl: "/contacto", evaluationLabel: "Agendar evaluación", footerNotice: "La información de este sitio es de carácter general y no sustituye una evaluación profesional individual." });
const literal = (value: unknown) => `'${(typeof value === "string" ? value : JSON.stringify(value)).replaceAll("'", "''")}'`;
let sql = "\n-- Idempotent initial content. Existing editorial records are never overwritten.\n";
for (const [index, page] of pages.entries()) {
  const sections = page.sections.map((section, sort_order) => blockSchema.parse({ ...section, id: randomUUID(), sort_order, is_enabled: true }));
  sql += `do $seed$ declare page_id uuid; begin\ninsert into public.cms_pages(slug,path,title,nav_label,status,show_in_navigation,navigation_order,published_at) values (${literal(page.slug)},${literal(page.path)},${literal(page.title)},${literal(page.nav_label)},'published',true,${index},now()) on conflict(slug) do nothing returning id into page_id;\nif page_id is not null then\n`;
  for (const section of sections) sql += `insert into public.cms_page_sections(page_id,section_type,data,sort_order,is_enabled) values (page_id,${literal(section.section_type)},${literal(section.data)}::jsonb,${section.sort_order},true);\n`;
  sql += "end if; end; $seed$;\n";
}
const columns = Object.keys(person);
const values = columns.map((column) => { const value = person[column as keyof typeof person]; return column === "credentials" ? `array[${person.credentials.map(literal).join(",")}]::text[]` : typeof value === "boolean" || typeof value === "number" ? String(value) : literal(value); });
sql += `insert into public.professionals(${columns.join(",")}) values (${values.join(",")}) on conflict(slug) do nothing;\n`;
sql += `insert into public.site_settings(id,data) values ('global',${literal(settings)}::jsonb) on conflict(id) do nothing;\n`;
const output = process.argv[2];
if (!output || !output.replaceAll("\\", "/").includes("supabase/migrations/")) throw new Error("Pass the migration path created by supabase migration new.");
const previous = await readFile(output, "utf8");
if (previous.includes("Idempotent initial content")) throw new Error("Seed already appended.");
await writeFile(output, previous + sql);
console.log(`Validated and seeded ${pages.length} pages, ${pages.reduce((sum, page) => sum + page.sections.length, 0)} blocks and 1 professional. No existing content overwritten.`);
